###
GET http://localhost:5454/users

###
POST http://localhost:5454/users
content-type: application/json

{
    "name": "sample",
    "email": "asdasd@gmail.com",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}